<?php
  function custom_follow_follow_networks_alter(&$networks, $uid = 0) {
    $networks[$uid]['etsy'] = array(
      'title' => '',
      'domain' => 'etsy.com',
      'type' => 'hidden',
    );

    $networks[$uid]['redbubble'] = array(
      'title' => '',
      'domain' => 'redbubble.com',
      'type' => 'hidden',
    );

    $networks[$uid]['facebook'] = array(
      'type' => 'hidden',
      'title' => '',
    );

  }
